language: node_js
node_js:
- 12
dist: trusty
addons:
  sonarcloud:
    organization: monojitb02
    token:
      secure: xFRSkclVOWcMeuQrxHqE5WKOIKf4B7GarjjCQM7hajMb6Y8xLmUciy5hnXiiI81NGJWbyisK61E3HxsBF7h64/pFeVb/CDIwlhwBxVT9JEpdtp5RBwnOpc22agAdbqZmMTYBG/z1BDNGM4AouVFNiYuRzhE4hNCsV63UDkCxafDfZBbzXYim4czBSXClGPGkE3pwtOrn+9ZTOsLzacFxsuWSdfYikIans8vu9vKM5XVVISQJDnlomJMyGOz5cA7Yk6+Is3OpZbYbok/wa6UtdiN8lkIinStug872Uxq8hreRdIpdhQuHAvGEKHUTnJ8qJt/HWKMqTn9Z4KFwvgKoeHqNwwam6Mq44f73z+KRDm/Nq+8evaxzdWNmQX//6cH17PD7Ew9qHwCa1jfqJoPQPLDlF/a/IwGjlJqmG6lfHQ5GaTXd0XRdxzZwOlOfD4cbPu68iQXvv6S0zyZBAMyYxjI0NKUdpEPPRm0MO8toatB8oeS6W6eMdyAfU40wn+pmQOO3kCatJxo8bFJCty9KtC0MrUXhBcvGYrFoLf6ZFOZJHoYCs92uFyn37Xrco10D1TJAk2XQd4qPND+CFyAFZA8YnCmqUh7uWdGstechH+t7rjwyamepHa2o1QPDYjUEpMAHuOksaiY7s/LwV9Nt7ZeAzk+sl6XQCTAI60ZWlYc=
script:
- npm run coverage
- sonar-scanner
notifications:
  slack:
    secure: Gi8sYXwB0nzljlgawBvwLuVvV8dQ0NSslcl8nR7+e+GQRFog5tcxoHPFTtV18BGB+pc/a+ffH4lyjhGlJKjDV5ONpXVXngGjy/MmcC+suB4IxGt58AXXqPtFoRKNyUjs+NqScDDAOMKzgP/7lBQb2oVLFlHfeVXGJnUo5FCUPblYvGHFJeAnd/ehk1eehl1nUw3T7mBFd1t6GyzRNgjeYhfxwYjJ8mgsFQvcSrz9rqV3F71+q6P/IdTi8L+7nw9teng7MZvFkjEfUYaIA1eVpUaFTxkbTr2U78z/4XO3uTm2pfCrQc0gFBYwskJJ/4gFqyTreLVf5R9E9oSbNi4d6DBCJri6wk22RdIOcI8BXJREcZkbtOVBSTjAOk94mu7Yd+5KTHfu3wqNzRoSsc8cf04YjwxuUrYNqwTW9R090Ayy+B8zkiR2qrBNgtJsC5tT7NWBZAc9RC9CgSdkRjT5recrD/HO+JTDJL0W2kJXHLZIUKYLK/FzDROjA8MtRa0jZbYpDbVnoD4SRqwfEXdvqy4PAe7TVJgBiTPsOD5zG5N7NuC/q9zhbBGCw/BRql9DDiZxYLgWPjgFss89P3ixXSb1mfQNv49S0fFIhvtV+AGad76ggVxpd8t/arpeEO08gI6nLyksdo1i+JF2bxXePYCjwXX8h7Z18Kvgri4i32c=
