# swagger configuration file

# values in the swagger hash are system configuration for swagger
swagger:
  mapErrorsToJson: true
  docEndpoints:
    raw: /api/project/service/v1/doc/swagger.json
    ui : /api/project/service/v1/doc

  fittingsDirs: [ middlewares ]
  defaultPipe: null
  swaggerControllerPipe: swagger_controllers  # defines the standard processing pipe for controllers

  # values defined in the bagpipes key are the bagpipes pipes and fittings definitions
  # (see https://github.com/apigee-127/bagpipes)
  bagpipes:

    _router:
      name: router-async-wrapper
      mockMode: false
      mockControllersDirs: [ mocks ]
      controllersDirs: [ controllers ]

    _swagger_validate:
      name: swagger_validator
      validateResponse: true


    # pipe for all swagger-node controllers
    swagger_controllers:
      - log-entry-middleware
      - cors
      - swagger_params_parser
      - swagger_security
      - assign-id-middleware
      - _swagger_validate
      - express_compatibility
      - set-logger-middleware
      - log-request-middleware
      - _router

    # pipe to serve swagger (endpoint is in swagger.yaml)
    swagger_raw:
      name: swagger_raw

# any other values in this file are just loaded into the config for application access...